a=input("Enter a string")
print("Length of the given string",len(a))
c=a.upper()
print("Upper case",c)
d=a.lower()
print("Lower case",d)
s=input("Enter the word to find count of occurance")
e=a.count(s)
print(f"The no of occurance of {s} in the given string is:",e)
